feat(enarxcall): ResetSgxPermissions
enarx/sallyport pull request #114
Opened 2022-03-10 03:25 UTC by jarkkojs

Add enarxcall for asking host to call EMODPR ioctl with PROT_NONE for the
given address range. Does not return error because on failure the the most
reasonable way to rollback is for host to kill the enclave.

Close: #113
Signed-off-by: Jarkko Sakkinen <jarkko@profian.com>

2022-03-10 04:12 UTC, jarkkojs commented
I found more elegant way: capture mprotect in the backend, do EMODPR there and continue with the syscall.

2022-03-10 12:17 UTC, jarkkojs commented
Re-opened because syscalls should not be intervened.

2022-03-10 12:23 UTC, rvolosatovs requested changes

2022-03-10 12:23 UTC, rvolosatovs commented on src/guest/handler.rs
> +    fn reset_sgx_permissions(&mut self, addr: *const u8, length: usize) -> Result<()> {
Please maintain lexicographic sorting of methods in the trait

2022-03-10 12:23 UTC, rvolosatovs commented on src/guest/call/enarxcall/reset_sgx_permissions.rs
> +    pub addr: *const u8,
Is there a reason this is not `NonNull`? Also, wouldn't `*mut c_void` be more appropriate?

2022-03-10 12:23 UTC, rvolosatovs commented on src/guest/call/enarxcall/reset_sgx_permissions.rs
> +impl<'a> Alloc<'a> for ResetSgxPermissions {
This could also implement `PassthroughAlloc` since no alllocation is taking place https://github.com/enarx/sallyport/blob/main/src/guest/call/enarxcall/passthrough.rs

2022-03-10 12:36 UTC, jarkkojs commented on src/guest/handler.rs
> +    fn reset_sgx_permissions(&mut self, addr: *const u8, length: usize) -> Result<()> {
OK I did not know there was such, I'll fix this.

2022-03-10 13:48 UTC, rvolosatovs approved these changes
@haraldh please check that signature makes sense (the `addr` argument in particular)

2022-03-10 13:48 UTC, rvolosatovs commented on tests/integration_tests/enarxcall.rs
> +fn reset_sgx_permissions() {
Let's have this one sorted as well for maintenance

2022-03-10 13:49 UTC, rvolosatovs commented on src/guest/call/enarxcall/reset_sgx_permissions.rs
> +impl PassthroughAlloc for ResetSgxPermissions {
All of these should reside in `passthrough.rs`

2022-03-10 13:49 UTC, rvolosatovs requested changes
See comments

2022-03-10 13:50 UTC, rvolosatovs commented on tests/integration_tests/enarxcall.rs
> +        use core::ptr::NonNull;
This can be imported at the top-level

2022-03-10 15:23 UTC, jarkkojs commented
I resolved the review comments.

2022-03-10 15:45 UTC, npmccallum requested changes, later dismissed
I'm requesting changes to block merge of this until the release.

2022-03-10 16:34 UTC, jarkkojs commented
> I'm requesting changes to block merge of this until the release.

Fine with me.

2022-03-10 19:38 UTC, rvolosatovs approved these changes, later dismissed

2022-03-11 17:19 UTC, jarkkojs commented
Converted to draft for now because it is not yet sure whether this will be needed or i.e. how mprotect() flow will work in the kernel side.

2022-03-21 14:34 UTC, rvolosatovs commented
What's the status of this?

2022-04-05 00:19 UTC, jarkkojs commented
We need this after all as by testing (not documented in Intel SDM). It is not possible to do RW -> RWX permission change.

2022-04-05 00:20 UTC, jarkkojs commented
ASAP merge preferred...

2022-04-05 09:36 UTC, rvolosatovs commented on tests/integration_tests/enarxcall.rs
> +        assert_eq!(handler.reset_sgx_permissions(addr, 0), Err(ENOSYS));
```diff
diff --git a/tests/integration_tests/enarxcall.rs b/tests/integration_tests/enarxcall.rs
index 25b6d364..4fd7dba2 100644
--- a/tests/integration_tests/enarxcall.rs
+++ b/tests/integration_tests/enarxcall.rs
@@ -65,11 +65,9 @@ fn mem_info() {
 #[test]
 fn reset_sgx_permissions() {
     run_test(2, [0xff; 16], move |_, _, handler| {
-        let addr = match NonNull::<libc::c_void>::new(0x7f8af78eb000 as *mut libc::c_void) {
-            Some(addr) => addr,
-            None => panic!(),
-        };
-
-        assert_eq!(handler.reset_sgx_permissions(addr, 0), Err(ENOSYS));
+        assert_eq!(
+            handler.reset_sgx_permissions(NonNull::new(0x7f8af78eb000 as *mut _).unwrap(), 0),
+            Err(ENOSYS)
+        );
     })
 }
```

2022-04-05 09:36 UTC, rvolosatovs commented on src/guest/handler.rs
> +    /// Set EPCM permissions to none.
I think we should document what `addr` and `length` represent here.
Is that an area of memory, for which the permissions are to be reset?

2022-04-05 10:17 UTC, jarkkojs commented
> I'm requesting changes to block merge of this until the release.

It's now required to get executable pages.

2022-04-05 10:19 UTC, rvolosatovs approved these changes, later dismissed

2022-04-05 10:19 UTC, rvolosatovs commented on src/guest/call/enarxcall/passthrough.rs
> +        Argv([self.addr.as_ptr() as usize, self.length])
```suggestion
        Argv([self.addr.as_ptr() as _, self.length])
```

2022-04-05 10:19 UTC, rvolosatovs commented on src/guest/handler.rs
> +    /// Within an address range, reset enclave permissions to 'read'.
I would expect the comment state something about the `length` being the byte length of the memory region starting at `addr`, but I guess this is also fine.
Are there any requirements on what `addr` values are valid? Are there requirements on what `length` values are valid?

2022-04-05 13:58 UTC, haraldh requested changes

2022-04-05 13:58 UTC, haraldh commented on tests/integration_tests/enarxcall.rs
> +            handler.reset_sgx_permissions(NonNull::new(0x7f8af78eb000 as *mut _).unwrap(), 0),
throws `EINVAL` because `length == 0`

2022-04-05 14:01 UTC, rvolosatovs commented on src/guest/handler.rs
> +        if addr.as_ptr() as usize & 0xfff != 0 || length == 0 || length & 0xfff != 0 {
this should be within `ResetSgxPermissions::stage` implementation.
The `PassthroughAlloc` trait should support fallible `stage()`

Let's file a follow-up issue about it

2022-04-05 15:46 UTC, jarkkojs commented on tests/integration_tests/enarxcall.rs
> +            handler.reset_sgx_permissions(NonNull::new(0x7f8af78eb000 as *mut _).unwrap(), 0),
thanks, fixed

2022-04-05 15:46 UTC, jarkkojs commented on src/guest/handler.rs
> +        if addr.as_ptr() as usize & 0xfff != 0 || length == 0 || length & 0xfff != 0 {
thanks, created an issue: https://github.com/enarx/sallyport/issues/142

2022-04-05 17:46 UTC, haraldh submitted a review, later dismissed

2022-04-06 05:12 UTC, jarkkojs commented
This is not required after all, so converting into draft mode up until that happens.

2022-04-11 12:40 UTC, rvolosatovs reviewed
overall, LGTM, can we please keep the calls and test cases sorted lexicographically? That is a very minor effort on implementor's side, but simplifies maintenance and makes code easier to navigate, especially as number of supported calls will grow

2022-04-11 13:09 UTC, jarkkojs commented
> overall, LGTM, can we please keep the calls and test cases sorted lexicographically? That is a very minor effort on implementor's side, but simplifies maintenance and makes code easier to navigate, especially as number of supported calls grows

can do

2022-04-11 13:20 UTC, rvolosatovs approved these changes

2022-04-11 19:05 UTC, merged