Using upstream `libc` for tests, unit tests on internal `libc`
enarx/sallyport pull request #132
Opened 2022-03-15 18:41 UTC by rjzak

Co-authored-by: Roman Volosatovs <roman@profian.com>
Signed-off-by: Richard Zak <richard@profian.com>

2022-03-15 18:53 UTC, rvolosatovs requested changes
There are still unit tests relying on in-crate `libc` constants that should be changed, e.g. https://github.com/enarx/sallyport/blob/ca03b82818705030a4c3a75789f4a72d583bab4f/src/guest/call/syscall/types/result/linux/x86_64.rs#L69

Please check all unit tests:
```
rg 'mod tests'   
src/item/syscall.rs
44:mod tests {

src/item/gdbcall.rs
64:mod tests {

src/item/block.rs
148:mod tests {

src/item/enarxcall/sgx.rs
188:mod tests {

src/item/enarxcall/mod.rs
62:mod tests {

src/host/mod.rs
102:mod tests {

src/guest/call/enarxcall/get_sgx_target_info.rs
43:mod tests {

src/guest/call/syscall/mod.rs
6:mod tests;

src/guest/alloc/mod.rs
6:mod tests;

src/guest/call/syscall/types/result/linux/x86_64.rs
67:mod tests {
```

2022-03-15 18:53 UTC, rvolosatovs commented on src/libc.rs
> +        //assert_eq!(libc::TIOCGWINSZ, super::TIOCGWINSZ, "TIOCGWINSZ");
Not something that necessarily needs to be removed, but these should already be implicitly tested by the integration tests; more importantly we should add tests for the structs, e.g. test that internal
```rust
timespec {
    tv_sec: 1,
    tv_nsec: 2,
}
```
transmuted to `libc::timespec` still contains the same field values

2022-03-15 18:53 UTC, rvolosatovs commented on Cargo.toml
> +doc = [ "gdbstub"]
This should not have been changed

2022-03-15 18:53 UTC, rvolosatovs commented on Cargo.toml
> -libc = { version = "0.2.119", default-features = false, optional = true }
We still need this for `doc` feature

2022-03-15 19:06 UTC, rjzak commented on Cargo.toml
> +doc = [ "gdbstub"]
It wouldn't compile otherwise without adding the `libc` crate at a dependency:
```
stdout : error: failed to parse manifest at `/home/rjzak/CLionProjects/sallyport/Cargo.toml`

Caused by:
  feature `doc` includes `libc`, but `libc` is not an optional dependency
  A non-optional dependency of the same name is defined; consider adding `optional = true` to its definition.
```

2022-03-16 14:21 UTC, rvolosatovs commented on Cargo.toml
> +libc = { version = "0.2.119", features = ["extra_traits"], optional = true }
This change is unnecessary

2022-03-16 14:21 UTC, rvolosatovs commented on src/libc.rs
> +
nit; redundant whitespace

2022-03-17 16:09 UTC, rjzak commented
Closing since I need to update on my end

2022-03-17 16:09 UTC, closed without merging