feat: add support for `clock_getres`
enarx/sallyport pull request #149
Opened 2022-04-07 16:54 UTC by rvolosatovs

Refs https://github.com/enarx/enarx/issues/1657

2022-04-07 17:36 UTC, haraldh requested changes

2022-04-07 17:36 UTC, haraldh commented on Cargo.toml
> +gdbstub = { version = "0", default-features = false, optional = true }
errr... anything else than 0.5 might be incompatible

2022-04-07 17:36 UTC, haraldh commented on Cargo.toml
> +goblin = { version = "0", default-features = false, features = [ "elf64" ] }
IDK... anything 0.x is basically an API change

2022-04-08 06:38 UTC, haraldh reviewed
Please move the `build(deps): use latest versions within major` to a separate PR, so we can discuss this there.

2022-04-08 06:38 UTC, haraldh commented on Cargo.toml
> +libc = { version = "0" }
If you do this, cargo is free to choose any version, which fits the rest of the dependencies. Therefore you have to specify the minimal version the crate supports.

Did you try this out using 
https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#minimal-versions
???

Also by saying `testaso = "0"` you imply that testaso `0.9` also works, which you don't know, because any `0.x` can break ABI and API.

2022-04-08 10:54 UTC, rvolosatovs commented
@haraldh #150

2022-04-08 10:57 UTC, haraldh approved these changes

2022-04-08 10:57 UTC, merged

2022-04-08 11:09 UTC, haraldh commented on Cargo.toml
> +libc = { version = "0.2", features = [ "extra_traits" ] }
Argh... this slipped in my review!!