[NOT READY FOR REVIEW] Add support for `recvfrom` syscall
enarx/sallyport pull request #47
Opened 2022-01-05 16:55 UTC by rvolosatovs

Part of #34
Blocked by #41 
TODO:
- [ ] Host-side implementation
- [ ] Tests

2022-01-21 13:56 UTC, rvolosatovs commented on src/v2/src/guest/handler.rs
> +                        slice::from_raw_parts_mut(src_addr.sa_data.as_mut_ptr(), *addrlen as _);
`sockaddr.sa_data` field is a `[c_char; 14]` https://docs.rs/libc/latest/libc/struct.sockaddr.html
`addrlen` may exceed 14, so potentially unvalidated memory region could be accessed if the platform does not handle this internally. Not sure if this is something we should worry about?

2022-01-21 20:44 UTC, rvolosatovs commented on src/v2/src/guest/handler.rs
> +                        slice::from_raw_parts_mut(src_addr.sa_data.as_mut_ptr(), *addrlen as _);
We could also count the field addresses here and validate the fields separately, if necessary. 0.1 does not seem to validate the `sa_data` length. https://github.com/enarx/sallyport/blob/12306c3f149a1ed2d19573c31342a0ba1d99e7c2/src/syscall/network.rs#L182-L209
@haraldh @npmccallum what do you think?

2022-01-24 14:13 UTC, haraldh commented on src/v2/src/guest/handler.rs
> +                        slice::from_raw_parts_mut(src_addr.sa_data.as_mut_ptr(), *addrlen as _);
IIRC sockaddr can be any of: https://docs.rs/libc/latest/libc/struct.sockaddr.html?search=libc%3A%3Asockaddr_
so for us, it's more like a `void *` and `*addrlen` is the length of the provided buffer.

So, we should only validate, that `*addrlen` from userspace is greater than the returned modified `*addrlen`

Take e.g. 

```
#define UNIX_PATH_MAX   108

struct sockaddr_un {
    __kernel_sa_family_t sun_family; /* AF_UNIX */
    char sun_path[UNIX_PATH_MAX];   /* pathname */
};
```

Which can be be up to 108 + sizeof(__kernel_sa_family_t) big.

Userspace would reserve the max size and the kernel would return the actual needed size for the PATH, IIRC.

2022-01-25 16:04 UTC, haraldh requested changes

2022-01-25 16:04 UTC, haraldh commented on src/v2/tests/integration_tests.rs
> +    });
You should save the handle and `join()` on it.

2022-01-25 16:05 UTC, haraldh requested changes

2022-01-25 16:05 UTC, haraldh commented on src/v2/tests/integration_tests.rs
> +const ADDR: &str = "127.0.0.1:8080";
What happens, if two developers on the same machine run the tests (or in parallel to the CI) ??

2022-01-25 16:54 UTC, rvolosatovs commented on src/v2/tests/integration_tests.rs
> +                    .send_to(EXPECTED.as_bytes(), addr)
I assume that in case `recvfrom` is not executed before `send_to` fires the packet would be buffered by the OS due to the bind, is that a valid assumption?
In other words, there is no race condition here, or is there?

2022-01-25 20:57 UTC, npmccallum commented
@rvolosatovs Please rebase.

2022-01-25 21:42 UTC, npmccallum commented on src/v2/src/lib.rs
> +pub(crate) const NULL: usize = usize::MAX;
I'm not sure I'm a fan of this patch. @haraldh Thoughts?

2022-01-25 22:40 UTC, rvolosatovs commented on src/v2/src/lib.rs
> +pub(crate) const NULL: usize = usize::MAX;
Alternative approach could be starting all offsets at `1` and treating `0` as `NULL`, would that be an improvement in your opinion?

2022-01-26 08:36 UTC, rvolosatovs commented on src/v2/src/lib.rs
> +pub(crate) const NULL: usize = usize::MAX;
I tried a few things and it appears that the cleanest approach is actually making this specific to `recvfrom` syscall. We don't need NULL for other syscalls (for now). This also aligns better with Rust model, as in we explicitly specify that `src_addr` is "nullable" in this case

2022-01-26 15:07 UTC, rvolosatovs commented on src/v2/src/guest/syscall/recvfrom.rs
> +    );
This will be refactored with similar approach as used in #67

2022-01-26 16:13 UTC, haraldh commented on src/v2/src/lib.rs
> +pub(crate) const NULL: usize = usize::MAX;
@npmccallum I like `usize::MAX` more than any other solution

2022-01-27 09:47 UTC, haraldh approved these changes

2022-01-27 09:47 UTC, haraldh commented on src/v2/tests/integration_tests.rs
> +                    .send_to(EXPECTED.as_bytes(), addr)
@rvolosatovs correct

2022-01-27 09:48 UTC, merged